//! Raw FFI bindings for the Corsair iCUE SDK v4.0.84.
//!
//! Generated by `bindgen` and post-processed per the README instructions.
//! See the [iCUE SDK repository](https://github.com/CorsairOfficial/cue-sdk) for documentation.

#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

use core::ffi::{c_char, c_int, c_uchar, c_uint, c_void};

// ---- Constants ----

pub const CORSAIR_STRING_SIZE_S: c_uint = 64;
pub const CORSAIR_STRING_SIZE_M: c_uint = 128;
pub const CORSAIR_LAYER_PRIORITY_MAX: c_uint = 255;
pub const CORSAIR_DEVICE_COUNT_MAX: c_uint = 64;
pub const CORSAIR_DEVICE_LEDCOUNT_MAX: c_uint = 512;

// ---- Type aliases ----

pub type CorsairDeviceId = [c_char; 128usize];
pub type CorsairLedLuid = c_uint;

// ---- Enum types (as integer type aliases with associated constants) ----

// CorsairError: contains shared list of all errors which could happen during calling of Corsair* functions
pub type CorsairError = c_uint;
pub const CorsairError_CE_Success: CorsairError = 0;
pub const CorsairError_CE_NotConnected: CorsairError = 1;
pub const CorsairError_CE_NoControl: CorsairError = 2;
pub const CorsairError_CE_IncompatibleProtocol: CorsairError = 3;
pub const CorsairError_CE_InvalidArguments: CorsairError = 4;
pub const CorsairError_CE_InvalidOperation: CorsairError = 5;
pub const CorsairError_CE_DeviceNotFound: CorsairError = 6;
pub const CorsairError_CE_NotAllowed: CorsairError = 7;

// CorsairSessionState: contains a list of all possible session states
pub type CorsairSessionState = c_uint;
pub const CorsairSessionState_CSS_Invalid: CorsairSessionState = 0;
pub const CorsairSessionState_CSS_Closed: CorsairSessionState = 1;
pub const CorsairSessionState_CSS_Connecting: CorsairSessionState = 2;
pub const CorsairSessionState_CSS_Timeout: CorsairSessionState = 3;
pub const CorsairSessionState_CSS_ConnectionRefused: CorsairSessionState = 4;
pub const CorsairSessionState_CSS_ConnectionLost: CorsairSessionState = 5;
pub const CorsairSessionState_CSS_Connected: CorsairSessionState = 6;

// CorsairDeviceType: contains list of available device types (bitmask)
pub type CorsairDeviceType = c_uint;
pub const CorsairDeviceType_CDT_Unknown: CorsairDeviceType = 0x0000;
pub const CorsairDeviceType_CDT_Keyboard: CorsairDeviceType = 0x0001;
pub const CorsairDeviceType_CDT_Mouse: CorsairDeviceType = 0x0002;
pub const CorsairDeviceType_CDT_Mousemat: CorsairDeviceType = 0x0004;
pub const CorsairDeviceType_CDT_Headset: CorsairDeviceType = 0x0008;
pub const CorsairDeviceType_CDT_HeadsetStand: CorsairDeviceType = 0x0010;
pub const CorsairDeviceType_CDT_FanLedController: CorsairDeviceType = 0x0020;
pub const CorsairDeviceType_CDT_LedController: CorsairDeviceType = 0x0040;
pub const CorsairDeviceType_CDT_MemoryModule: CorsairDeviceType = 0x0080;
pub const CorsairDeviceType_CDT_Cooler: CorsairDeviceType = 0x0100;
pub const CorsairDeviceType_CDT_Motherboard: CorsairDeviceType = 0x0200;
pub const CorsairDeviceType_CDT_GraphicsCard: CorsairDeviceType = 0x0400;
pub const CorsairDeviceType_CDT_Touchbar: CorsairDeviceType = 0x0800;
pub const CorsairDeviceType_CDT_GameController: CorsairDeviceType = 0x1000;
pub const CorsairDeviceType_CDT_All: CorsairDeviceType = 0xFFFFFFFF;

// CorsairEventId: contains list of event identifiers
pub type CorsairEventId = c_uint;
pub const CorsairEventId_CEI_Invalid: CorsairEventId = 0;
pub const CorsairEventId_CEI_DeviceConnectionStatusChangedEvent: CorsairEventId = 1;
pub const CorsairEventId_CEI_KeyEvent: CorsairEventId = 2;

// CorsairMacroKeyId: contains a shared list of G, M and S keys
pub type CorsairMacroKeyId = c_uint;
pub const CorsairMacroKeyId_CMKI_Invalid: CorsairMacroKeyId = 0;
pub const CorsairMacroKeyId_CMKI_1: CorsairMacroKeyId = 1;
pub const CorsairMacroKeyId_CMKI_2: CorsairMacroKeyId = 2;
pub const CorsairMacroKeyId_CMKI_3: CorsairMacroKeyId = 3;
pub const CorsairMacroKeyId_CMKI_4: CorsairMacroKeyId = 4;
pub const CorsairMacroKeyId_CMKI_5: CorsairMacroKeyId = 5;
pub const CorsairMacroKeyId_CMKI_6: CorsairMacroKeyId = 6;
pub const CorsairMacroKeyId_CMKI_7: CorsairMacroKeyId = 7;
pub const CorsairMacroKeyId_CMKI_8: CorsairMacroKeyId = 8;
pub const CorsairMacroKeyId_CMKI_9: CorsairMacroKeyId = 9;
pub const CorsairMacroKeyId_CMKI_10: CorsairMacroKeyId = 10;
pub const CorsairMacroKeyId_CMKI_11: CorsairMacroKeyId = 11;
pub const CorsairMacroKeyId_CMKI_12: CorsairMacroKeyId = 12;
pub const CorsairMacroKeyId_CMKI_13: CorsairMacroKeyId = 13;
pub const CorsairMacroKeyId_CMKI_14: CorsairMacroKeyId = 14;
pub const CorsairMacroKeyId_CMKI_15: CorsairMacroKeyId = 15;
pub const CorsairMacroKeyId_CMKI_16: CorsairMacroKeyId = 16;
pub const CorsairMacroKeyId_CMKI_17: CorsairMacroKeyId = 17;
pub const CorsairMacroKeyId_CMKI_18: CorsairMacroKeyId = 18;
pub const CorsairMacroKeyId_CMKI_19: CorsairMacroKeyId = 19;
pub const CorsairMacroKeyId_CMKI_20: CorsairMacroKeyId = 20;

// CorsairDevicePropertyId: contains list of property identifiers which can be read from device
pub type CorsairDevicePropertyId = c_uint;
pub const CorsairDevicePropertyId_CDPI_Invalid: CorsairDevicePropertyId = 0;
pub const CorsairDevicePropertyId_CDPI_PropertyArray: CorsairDevicePropertyId = 1;
pub const CorsairDevicePropertyId_CDPI_MicEnabled: CorsairDevicePropertyId = 2;
pub const CorsairDevicePropertyId_CDPI_SurroundSoundEnabled: CorsairDevicePropertyId = 3;
pub const CorsairDevicePropertyId_CDPI_SidetoneEnabled: CorsairDevicePropertyId = 4;
pub const CorsairDevicePropertyId_CDPI_EqualizerPreset: CorsairDevicePropertyId = 5;
pub const CorsairDevicePropertyId_CDPI_PhysicalLayout: CorsairDevicePropertyId = 6;
pub const CorsairDevicePropertyId_CDPI_LogicalLayout: CorsairDevicePropertyId = 7;
pub const CorsairDevicePropertyId_CDPI_MacroKeyArray: CorsairDevicePropertyId = 8;
pub const CorsairDevicePropertyId_CDPI_BatteryLevel: CorsairDevicePropertyId = 9;
pub const CorsairDevicePropertyId_CDPI_ChannelLedCount: CorsairDevicePropertyId = 10;
pub const CorsairDevicePropertyId_CDPI_ChannelDeviceCount: CorsairDevicePropertyId = 11;
pub const CorsairDevicePropertyId_CDPI_ChannelDeviceLedCountArray: CorsairDevicePropertyId = 12;
pub const CorsairDevicePropertyId_CDPI_ChannelDeviceTypeArray: CorsairDevicePropertyId = 13;

// CorsairDataType: contains list of available property types
pub type CorsairDataType = c_uint;
pub const CorsairDataType_CT_Boolean: CorsairDataType = 0;
pub const CorsairDataType_CT_Int32: CorsairDataType = 1;
pub const CorsairDataType_CT_Float64: CorsairDataType = 2;
pub const CorsairDataType_CT_String: CorsairDataType = 3;
pub const CorsairDataType_CT_Boolean_Array: CorsairDataType = 16;
pub const CorsairDataType_CT_Int32_Array: CorsairDataType = 17;
pub const CorsairDataType_CT_Float64_Array: CorsairDataType = 18;
pub const CorsairDataType_CT_String_Array: CorsairDataType = 19;

// CorsairPropertyFlag: contains list of operations that can be applied to the property
pub type CorsairPropertyFlag = c_uint;
pub const CorsairPropertyFlag_CPF_None: CorsairPropertyFlag = 0;
pub const CorsairPropertyFlag_CPF_CanRead: CorsairPropertyFlag = 1;
pub const CorsairPropertyFlag_CPF_CanWrite: CorsairPropertyFlag = 2;
pub const CorsairPropertyFlag_CPF_Indexed: CorsairPropertyFlag = 4;

// CorsairPhysicalLayout: contains list of available physical layouts for keyboards
pub type CorsairPhysicalLayout = c_uint;
pub const CorsairPhysicalLayout_CPL_Invalid: CorsairPhysicalLayout = 0;
pub const CorsairPhysicalLayout_CPL_US: CorsairPhysicalLayout = 1;
pub const CorsairPhysicalLayout_CPL_UK: CorsairPhysicalLayout = 2;
pub const CorsairPhysicalLayout_CPL_JP: CorsairPhysicalLayout = 3;
pub const CorsairPhysicalLayout_CPL_KR: CorsairPhysicalLayout = 4;
pub const CorsairPhysicalLayout_CPL_BR: CorsairPhysicalLayout = 5;

// CorsairLogicalLayout: contains list of available logical layouts for keyboards
pub type CorsairLogicalLayout = c_uint;
pub const CorsairLogicalLayout_CLL_Invalid: CorsairLogicalLayout = 0;
pub const CorsairLogicalLayout_CLL_US_Int: CorsairLogicalLayout = 1;
pub const CorsairLogicalLayout_CLL_NA: CorsairLogicalLayout = 2;
pub const CorsairLogicalLayout_CLL_EU: CorsairLogicalLayout = 3;
pub const CorsairLogicalLayout_CLL_UK: CorsairLogicalLayout = 4;
pub const CorsairLogicalLayout_CLL_BE: CorsairLogicalLayout = 5;
pub const CorsairLogicalLayout_CLL_BR: CorsairLogicalLayout = 6;
pub const CorsairLogicalLayout_CLL_CH: CorsairLogicalLayout = 7;
pub const CorsairLogicalLayout_CLL_CN: CorsairLogicalLayout = 8;
pub const CorsairLogicalLayout_CLL_DE: CorsairLogicalLayout = 9;
pub const CorsairLogicalLayout_CLL_ES: CorsairLogicalLayout = 10;
pub const CorsairLogicalLayout_CLL_FR: CorsairLogicalLayout = 11;
pub const CorsairLogicalLayout_CLL_IT: CorsairLogicalLayout = 12;
pub const CorsairLogicalLayout_CLL_ND: CorsairLogicalLayout = 13;
pub const CorsairLogicalLayout_CLL_RU: CorsairLogicalLayout = 14;
pub const CorsairLogicalLayout_CLL_JP: CorsairLogicalLayout = 15;
pub const CorsairLogicalLayout_CLL_KR: CorsairLogicalLayout = 16;
pub const CorsairLogicalLayout_CLL_TW: CorsairLogicalLayout = 17;
pub const CorsairLogicalLayout_CLL_MEX: CorsairLogicalLayout = 18;

// CorsairChannelDeviceType: contains list of LED-devices which can be connected to DIY-device
pub type CorsairChannelDeviceType = c_uint;
pub const CorsairChannelDeviceType_CCDT_Invalid: CorsairChannelDeviceType = 0;
pub const CorsairChannelDeviceType_CCDT_HD_Fan: CorsairChannelDeviceType = 1;
pub const CorsairChannelDeviceType_CCDT_SP_Fan: CorsairChannelDeviceType = 2;
pub const CorsairChannelDeviceType_CCDT_LL_Fan: CorsairChannelDeviceType = 3;
pub const CorsairChannelDeviceType_CCDT_ML_Fan: CorsairChannelDeviceType = 4;
pub const CorsairChannelDeviceType_CCDT_QL_Fan: CorsairChannelDeviceType = 5;
pub const CorsairChannelDeviceType_CCDT_8LedSeriesFan: CorsairChannelDeviceType = 6;
pub const CorsairChannelDeviceType_CCDT_Strip: CorsairChannelDeviceType = 7;
pub const CorsairChannelDeviceType_CCDT_DAP: CorsairChannelDeviceType = 8;
pub const CorsairChannelDeviceType_CCDT_Pump: CorsairChannelDeviceType = 9;
pub const CorsairChannelDeviceType_CCDT_DRAM: CorsairChannelDeviceType = 10;
pub const CorsairChannelDeviceType_CCDT_WaterBlock: CorsairChannelDeviceType = 11;
pub const CorsairChannelDeviceType_CCDT_QX_Fan: CorsairChannelDeviceType = 12;

// CorsairAccessLevel: contains list of available SDK access levels
pub type CorsairAccessLevel = c_uint;
pub const CorsairAccessLevel_CAL_Shared: CorsairAccessLevel = 0;
pub const CorsairAccessLevel_CAL_ExclusiveLightingControl: CorsairAccessLevel = 1;
pub const CorsairAccessLevel_CAL_ExclusiveKeyEventsListening: CorsairAccessLevel = 2;
pub const CorsairAccessLevel_CAL_ExclusiveLightingControlAndKeyEventsListening: CorsairAccessLevel =
    3;

// CorsairLedGroup: contains a list of led groups
pub type CorsairLedGroup = c_uint;
pub const CorsairLedGroup_CLG_Keyboard: CorsairLedGroup = 0;
pub const CorsairLedGroup_CLG_KeyboardGKeys: CorsairLedGroup = 1;
pub const CorsairLedGroup_CLG_KeyboardEdge: CorsairLedGroup = 2;
pub const CorsairLedGroup_CLG_KeyboardOem: CorsairLedGroup = 3;
pub const CorsairLedGroup_CLG_Mouse: CorsairLedGroup = 4;
pub const CorsairLedGroup_CLG_Mousemat: CorsairLedGroup = 5;
pub const CorsairLedGroup_CLG_Headset: CorsairLedGroup = 6;
pub const CorsairLedGroup_CLG_HeadsetStand: CorsairLedGroup = 7;
pub const CorsairLedGroup_CLG_MemoryModule: CorsairLedGroup = 8;
pub const CorsairLedGroup_CLG_Motherboard: CorsairLedGroup = 9;
pub const CorsairLedGroup_CLG_GraphicsCard: CorsairLedGroup = 10;
pub const CorsairLedGroup_CLG_DIY_Channel1: CorsairLedGroup = 11;
pub const CorsairLedGroup_CLG_DIY_Channel2: CorsairLedGroup = 12;
pub const CorsairLedGroup_CLG_DIY_Channel3: CorsairLedGroup = 13;
pub const CorsairLedGroup_CLG_Touchbar: CorsairLedGroup = 14;
pub const CorsairLedGroup_CLG_GameController: CorsairLedGroup = 15;

// CorsairLedId_Keyboard: contains a list of keyboard leds that belong to CLG_Keyboard group
pub type CorsairLedId_Keyboard = c_uint;
pub const CorsairLedId_Keyboard_CLK_Invalid: CorsairLedId_Keyboard = 0;
pub const CorsairLedId_Keyboard_CLK_Escape: CorsairLedId_Keyboard = 1;
pub const CorsairLedId_Keyboard_CLK_F1: CorsairLedId_Keyboard = 2;
pub const CorsairLedId_Keyboard_CLK_F2: CorsairLedId_Keyboard = 3;
pub const CorsairLedId_Keyboard_CLK_F3: CorsairLedId_Keyboard = 4;
pub const CorsairLedId_Keyboard_CLK_F4: CorsairLedId_Keyboard = 5;
pub const CorsairLedId_Keyboard_CLK_F5: CorsairLedId_Keyboard = 6;
pub const CorsairLedId_Keyboard_CLK_F6: CorsairLedId_Keyboard = 7;
pub const CorsairLedId_Keyboard_CLK_F7: CorsairLedId_Keyboard = 8;
pub const CorsairLedId_Keyboard_CLK_F8: CorsairLedId_Keyboard = 9;
pub const CorsairLedId_Keyboard_CLK_F9: CorsairLedId_Keyboard = 10;
pub const CorsairLedId_Keyboard_CLK_F10: CorsairLedId_Keyboard = 11;
pub const CorsairLedId_Keyboard_CLK_F11: CorsairLedId_Keyboard = 12;
pub const CorsairLedId_Keyboard_CLK_F12: CorsairLedId_Keyboard = 13;
pub const CorsairLedId_Keyboard_CLK_GraveAccentAndTilde: CorsairLedId_Keyboard = 14;
pub const CorsairLedId_Keyboard_CLK_1: CorsairLedId_Keyboard = 15;
pub const CorsairLedId_Keyboard_CLK_2: CorsairLedId_Keyboard = 16;
pub const CorsairLedId_Keyboard_CLK_3: CorsairLedId_Keyboard = 17;
pub const CorsairLedId_Keyboard_CLK_4: CorsairLedId_Keyboard = 18;
pub const CorsairLedId_Keyboard_CLK_5: CorsairLedId_Keyboard = 19;
pub const CorsairLedId_Keyboard_CLK_6: CorsairLedId_Keyboard = 20;
pub const CorsairLedId_Keyboard_CLK_7: CorsairLedId_Keyboard = 21;
pub const CorsairLedId_Keyboard_CLK_8: CorsairLedId_Keyboard = 22;
pub const CorsairLedId_Keyboard_CLK_9: CorsairLedId_Keyboard = 23;
pub const CorsairLedId_Keyboard_CLK_0: CorsairLedId_Keyboard = 24;
pub const CorsairLedId_Keyboard_CLK_MinusAndUnderscore: CorsairLedId_Keyboard = 25;
pub const CorsairLedId_Keyboard_CLK_EqualsAndPlus: CorsairLedId_Keyboard = 26;
pub const CorsairLedId_Keyboard_CLK_Backspace: CorsairLedId_Keyboard = 27;
pub const CorsairLedId_Keyboard_CLK_Tab: CorsairLedId_Keyboard = 28;
pub const CorsairLedId_Keyboard_CLK_Q: CorsairLedId_Keyboard = 29;
pub const CorsairLedId_Keyboard_CLK_W: CorsairLedId_Keyboard = 30;
pub const CorsairLedId_Keyboard_CLK_E: CorsairLedId_Keyboard = 31;
pub const CorsairLedId_Keyboard_CLK_R: CorsairLedId_Keyboard = 32;
pub const CorsairLedId_Keyboard_CLK_T: CorsairLedId_Keyboard = 33;
pub const CorsairLedId_Keyboard_CLK_Y: CorsairLedId_Keyboard = 34;
pub const CorsairLedId_Keyboard_CLK_U: CorsairLedId_Keyboard = 35;
pub const CorsairLedId_Keyboard_CLK_I: CorsairLedId_Keyboard = 36;
pub const CorsairLedId_Keyboard_CLK_O: CorsairLedId_Keyboard = 37;
pub const CorsairLedId_Keyboard_CLK_P: CorsairLedId_Keyboard = 38;
pub const CorsairLedId_Keyboard_CLK_BracketLeft: CorsairLedId_Keyboard = 39;
pub const CorsairLedId_Keyboard_CLK_BracketRight: CorsairLedId_Keyboard = 40;
pub const CorsairLedId_Keyboard_CLK_CapsLock: CorsairLedId_Keyboard = 41;
pub const CorsairLedId_Keyboard_CLK_A: CorsairLedId_Keyboard = 42;
pub const CorsairLedId_Keyboard_CLK_S: CorsairLedId_Keyboard = 43;
pub const CorsairLedId_Keyboard_CLK_D: CorsairLedId_Keyboard = 44;
pub const CorsairLedId_Keyboard_CLK_F: CorsairLedId_Keyboard = 45;
pub const CorsairLedId_Keyboard_CLK_G: CorsairLedId_Keyboard = 46;
pub const CorsairLedId_Keyboard_CLK_H: CorsairLedId_Keyboard = 47;
pub const CorsairLedId_Keyboard_CLK_J: CorsairLedId_Keyboard = 48;
pub const CorsairLedId_Keyboard_CLK_K: CorsairLedId_Keyboard = 49;
pub const CorsairLedId_Keyboard_CLK_L: CorsairLedId_Keyboard = 50;
pub const CorsairLedId_Keyboard_CLK_SemicolonAndColon: CorsairLedId_Keyboard = 51;
pub const CorsairLedId_Keyboard_CLK_ApostropheAndDoubleQuote: CorsairLedId_Keyboard = 52;
pub const CorsairLedId_Keyboard_CLK_Backslash: CorsairLedId_Keyboard = 53;
pub const CorsairLedId_Keyboard_CLK_Enter: CorsairLedId_Keyboard = 54;
pub const CorsairLedId_Keyboard_CLK_LeftShift: CorsairLedId_Keyboard = 55;
pub const CorsairLedId_Keyboard_CLK_NonUsBackslash: CorsairLedId_Keyboard = 56;
pub const CorsairLedId_Keyboard_CLK_Z: CorsairLedId_Keyboard = 57;
pub const CorsairLedId_Keyboard_CLK_X: CorsairLedId_Keyboard = 58;
pub const CorsairLedId_Keyboard_CLK_C: CorsairLedId_Keyboard = 59;
pub const CorsairLedId_Keyboard_CLK_V: CorsairLedId_Keyboard = 60;
pub const CorsairLedId_Keyboard_CLK_B: CorsairLedId_Keyboard = 61;
pub const CorsairLedId_Keyboard_CLK_N: CorsairLedId_Keyboard = 62;
pub const CorsairLedId_Keyboard_CLK_M: CorsairLedId_Keyboard = 63;
pub const CorsairLedId_Keyboard_CLK_CommaAndLessThan: CorsairLedId_Keyboard = 64;
pub const CorsairLedId_Keyboard_CLK_PeriodAndBiggerThan: CorsairLedId_Keyboard = 65;
pub const CorsairLedId_Keyboard_CLK_SlashAndQuestionMark: CorsairLedId_Keyboard = 66;
pub const CorsairLedId_Keyboard_CLK_RightShift: CorsairLedId_Keyboard = 67;
pub const CorsairLedId_Keyboard_CLK_LeftCtrl: CorsairLedId_Keyboard = 68;
pub const CorsairLedId_Keyboard_CLK_LeftGui: CorsairLedId_Keyboard = 69;
pub const CorsairLedId_Keyboard_CLK_LeftAlt: CorsairLedId_Keyboard = 70;
pub const CorsairLedId_Keyboard_CLK_Space: CorsairLedId_Keyboard = 71;
pub const CorsairLedId_Keyboard_CLK_RightAlt: CorsairLedId_Keyboard = 72;
pub const CorsairLedId_Keyboard_CLK_RightGui: CorsairLedId_Keyboard = 73;
pub const CorsairLedId_Keyboard_CLK_Application: CorsairLedId_Keyboard = 74;
pub const CorsairLedId_Keyboard_CLK_RightCtrl: CorsairLedId_Keyboard = 75;
pub const CorsairLedId_Keyboard_CLK_LedProgramming: CorsairLedId_Keyboard = 76;
pub const CorsairLedId_Keyboard_CLK_Lang1: CorsairLedId_Keyboard = 77;
pub const CorsairLedId_Keyboard_CLK_Lang2: CorsairLedId_Keyboard = 78;
pub const CorsairLedId_Keyboard_CLK_International1: CorsairLedId_Keyboard = 79;
pub const CorsairLedId_Keyboard_CLK_International2: CorsairLedId_Keyboard = 80;
pub const CorsairLedId_Keyboard_CLK_International3: CorsairLedId_Keyboard = 81;
pub const CorsairLedId_Keyboard_CLK_International4: CorsairLedId_Keyboard = 82;
pub const CorsairLedId_Keyboard_CLK_International5: CorsairLedId_Keyboard = 83;
pub const CorsairLedId_Keyboard_CLK_PrintScreen: CorsairLedId_Keyboard = 84;
pub const CorsairLedId_Keyboard_CLK_ScrollLock: CorsairLedId_Keyboard = 85;
pub const CorsairLedId_Keyboard_CLK_PauseBreak: CorsairLedId_Keyboard = 86;
pub const CorsairLedId_Keyboard_CLK_Insert: CorsairLedId_Keyboard = 87;
pub const CorsairLedId_Keyboard_CLK_Home: CorsairLedId_Keyboard = 88;
pub const CorsairLedId_Keyboard_CLK_PageUp: CorsairLedId_Keyboard = 89;
pub const CorsairLedId_Keyboard_CLK_Delete: CorsairLedId_Keyboard = 90;
pub const CorsairLedId_Keyboard_CLK_End: CorsairLedId_Keyboard = 91;
pub const CorsairLedId_Keyboard_CLK_PageDown: CorsairLedId_Keyboard = 92;
pub const CorsairLedId_Keyboard_CLK_UpArrow: CorsairLedId_Keyboard = 93;
pub const CorsairLedId_Keyboard_CLK_LeftArrow: CorsairLedId_Keyboard = 94;
pub const CorsairLedId_Keyboard_CLK_DownArrow: CorsairLedId_Keyboard = 95;
pub const CorsairLedId_Keyboard_CLK_RightArrow: CorsairLedId_Keyboard = 96;
pub const CorsairLedId_Keyboard_CLK_NonUsTilde: CorsairLedId_Keyboard = 97;
pub const CorsairLedId_Keyboard_CLK_Brightness: CorsairLedId_Keyboard = 98;
pub const CorsairLedId_Keyboard_CLK_WinLock: CorsairLedId_Keyboard = 99;
pub const CorsairLedId_Keyboard_CLK_Mute: CorsairLedId_Keyboard = 100;
pub const CorsairLedId_Keyboard_CLK_Stop: CorsairLedId_Keyboard = 101;
pub const CorsairLedId_Keyboard_CLK_ScanPreviousTrack: CorsairLedId_Keyboard = 102;
pub const CorsairLedId_Keyboard_CLK_PlayPause: CorsairLedId_Keyboard = 103;
pub const CorsairLedId_Keyboard_CLK_ScanNextTrack: CorsairLedId_Keyboard = 104;
pub const CorsairLedId_Keyboard_CLK_NumLock: CorsairLedId_Keyboard = 105;
pub const CorsairLedId_Keyboard_CLK_KeypadSlash: CorsairLedId_Keyboard = 106;
pub const CorsairLedId_Keyboard_CLK_KeypadAsterisk: CorsairLedId_Keyboard = 107;
pub const CorsairLedId_Keyboard_CLK_KeypadMinus: CorsairLedId_Keyboard = 108;
pub const CorsairLedId_Keyboard_CLK_Keypad7: CorsairLedId_Keyboard = 109;
pub const CorsairLedId_Keyboard_CLK_Keypad8: CorsairLedId_Keyboard = 110;
pub const CorsairLedId_Keyboard_CLK_Keypad9: CorsairLedId_Keyboard = 111;
pub const CorsairLedId_Keyboard_CLK_KeypadPlus: CorsairLedId_Keyboard = 112;
pub const CorsairLedId_Keyboard_CLK_Keypad4: CorsairLedId_Keyboard = 113;
pub const CorsairLedId_Keyboard_CLK_Keypad5: CorsairLedId_Keyboard = 114;
pub const CorsairLedId_Keyboard_CLK_Keypad6: CorsairLedId_Keyboard = 115;
pub const CorsairLedId_Keyboard_CLK_Keypad1: CorsairLedId_Keyboard = 116;
pub const CorsairLedId_Keyboard_CLK_Keypad2: CorsairLedId_Keyboard = 117;
pub const CorsairLedId_Keyboard_CLK_Keypad3: CorsairLedId_Keyboard = 118;
pub const CorsairLedId_Keyboard_CLK_KeypadComma: CorsairLedId_Keyboard = 119;
pub const CorsairLedId_Keyboard_CLK_KeypadEnter: CorsairLedId_Keyboard = 120;
pub const CorsairLedId_Keyboard_CLK_Keypad0: CorsairLedId_Keyboard = 121;
pub const CorsairLedId_Keyboard_CLK_KeypadPeriodAndDelete: CorsairLedId_Keyboard = 122;
pub const CorsairLedId_Keyboard_CLK_VolumeUp: CorsairLedId_Keyboard = 123;
pub const CorsairLedId_Keyboard_CLK_VolumeDown: CorsairLedId_Keyboard = 124;
pub const CorsairLedId_Keyboard_CLK_MR: CorsairLedId_Keyboard = 125;
pub const CorsairLedId_Keyboard_CLK_M1: CorsairLedId_Keyboard = 126;
pub const CorsairLedId_Keyboard_CLK_M2: CorsairLedId_Keyboard = 127;
pub const CorsairLedId_Keyboard_CLK_M3: CorsairLedId_Keyboard = 128;
pub const CorsairLedId_Keyboard_CLK_Fn: CorsairLedId_Keyboard = 129;

// ---- Structs ----

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairVersion {
    pub major: c_int,
    pub minor: c_int,
    pub patch: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairVersion"][::std::mem::size_of::<CorsairVersion>() - 12usize];
    ["Alignment of CorsairVersion"][::std::mem::align_of::<CorsairVersion>() - 4usize];
    ["Offset of field: CorsairVersion::major"]
        [::std::mem::offset_of!(CorsairVersion, major) - 0usize];
    ["Offset of field: CorsairVersion::minor"]
        [::std::mem::offset_of!(CorsairVersion, minor) - 4usize];
    ["Offset of field: CorsairVersion::patch"]
        [::std::mem::offset_of!(CorsairVersion, patch) - 8usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairSessionDetails {
    pub clientVersion: CorsairVersion,
    pub serverVersion: CorsairVersion,
    pub serverHostVersion: CorsairVersion,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairSessionDetails"][::std::mem::size_of::<CorsairSessionDetails>() - 36usize];
    ["Alignment of CorsairSessionDetails"]
        [::std::mem::align_of::<CorsairSessionDetails>() - 4usize];
    ["Offset of field: CorsairSessionDetails::clientVersion"]
        [::std::mem::offset_of!(CorsairSessionDetails, clientVersion) - 0usize];
    ["Offset of field: CorsairSessionDetails::serverVersion"]
        [::std::mem::offset_of!(CorsairSessionDetails, serverVersion) - 12usize];
    ["Offset of field: CorsairSessionDetails::serverHostVersion"]
        [::std::mem::offset_of!(CorsairSessionDetails, serverHostVersion) - 24usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairSessionStateChanged {
    pub state: CorsairSessionState,
    pub details: CorsairSessionDetails,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairSessionStateChanged"]
        [::std::mem::size_of::<CorsairSessionStateChanged>() - 40usize];
    ["Alignment of CorsairSessionStateChanged"]
        [::std::mem::align_of::<CorsairSessionStateChanged>() - 4usize];
    ["Offset of field: CorsairSessionStateChanged::state"]
        [::std::mem::offset_of!(CorsairSessionStateChanged, state) - 0usize];
    ["Offset of field: CorsairSessionStateChanged::details"]
        [::std::mem::offset_of!(CorsairSessionStateChanged, details) - 4usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDeviceInfo {
    pub type_: CorsairDeviceType,
    pub id: CorsairDeviceId,
    pub serial: [c_char; 128usize],
    pub model: [c_char; 128usize],
    pub ledCount: c_int,
    pub channelCount: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDeviceInfo"][::std::mem::size_of::<CorsairDeviceInfo>() - 396usize];
    ["Alignment of CorsairDeviceInfo"][::std::mem::align_of::<CorsairDeviceInfo>() - 4usize];
    ["Offset of field: CorsairDeviceInfo::type_"]
        [::std::mem::offset_of!(CorsairDeviceInfo, type_) - 0usize];
    ["Offset of field: CorsairDeviceInfo::id"]
        [::std::mem::offset_of!(CorsairDeviceInfo, id) - 4usize];
    ["Offset of field: CorsairDeviceInfo::serial"]
        [::std::mem::offset_of!(CorsairDeviceInfo, serial) - 132usize];
    ["Offset of field: CorsairDeviceInfo::model"]
        [::std::mem::offset_of!(CorsairDeviceInfo, model) - 260usize];
    ["Offset of field: CorsairDeviceInfo::ledCount"]
        [::std::mem::offset_of!(CorsairDeviceInfo, ledCount) - 388usize];
    ["Offset of field: CorsairDeviceInfo::channelCount"]
        [::std::mem::offset_of!(CorsairDeviceInfo, channelCount) - 392usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairLedPosition {
    pub id: CorsairLedLuid,
    pub cx: f64,
    pub cy: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairLedPosition"][::std::mem::size_of::<CorsairLedPosition>() - 24usize];
    ["Alignment of CorsairLedPosition"][::std::mem::align_of::<CorsairLedPosition>() - 8usize];
    ["Offset of field: CorsairLedPosition::id"]
        [::std::mem::offset_of!(CorsairLedPosition, id) - 0usize];
    ["Offset of field: CorsairLedPosition::cx"]
        [::std::mem::offset_of!(CorsairLedPosition, cx) - 8usize];
    ["Offset of field: CorsairLedPosition::cy"]
        [::std::mem::offset_of!(CorsairLedPosition, cy) - 16usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDeviceFilter {
    pub deviceTypeMask: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDeviceFilter"][::std::mem::size_of::<CorsairDeviceFilter>() - 4usize];
    ["Alignment of CorsairDeviceFilter"][::std::mem::align_of::<CorsairDeviceFilter>() - 4usize];
    ["Offset of field: CorsairDeviceFilter::deviceTypeMask"]
        [::std::mem::offset_of!(CorsairDeviceFilter, deviceTypeMask) - 0usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDeviceConnectionStatusChangedEvent {
    pub deviceId: CorsairDeviceId,
    pub isConnected: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDeviceConnectionStatusChangedEvent"]
        [::std::mem::size_of::<CorsairDeviceConnectionStatusChangedEvent>() - 129usize];
    ["Alignment of CorsairDeviceConnectionStatusChangedEvent"]
        [::std::mem::align_of::<CorsairDeviceConnectionStatusChangedEvent>() - 1usize];
    ["Offset of field: CorsairDeviceConnectionStatusChangedEvent::deviceId"]
        [::std::mem::offset_of!(CorsairDeviceConnectionStatusChangedEvent, deviceId) - 0usize];
    ["Offset of field: CorsairDeviceConnectionStatusChangedEvent::isConnected"]
        [::std::mem::offset_of!(CorsairDeviceConnectionStatusChangedEvent, isConnected) - 128usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairKeyEvent {
    pub deviceId: CorsairDeviceId,
    pub keyId: CorsairMacroKeyId,
    pub isPressed: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairKeyEvent"][::std::mem::size_of::<CorsairKeyEvent>() - 136usize];
    ["Alignment of CorsairKeyEvent"][::std::mem::align_of::<CorsairKeyEvent>() - 4usize];
    ["Offset of field: CorsairKeyEvent::deviceId"]
        [::std::mem::offset_of!(CorsairKeyEvent, deviceId) - 0usize];
    ["Offset of field: CorsairKeyEvent::keyId"]
        [::std::mem::offset_of!(CorsairKeyEvent, keyId) - 128usize];
    ["Offset of field: CorsairKeyEvent::isPressed"]
        [::std::mem::offset_of!(CorsairKeyEvent, isPressed) - 132usize];
};

// CorsairEvent contains an anonymous union in C; we name it CorsairEventUnion here.
// SAFETY: The iCUE SDK documentation states the SDK is thread-safe, so we implement
// Send and Sync for types containing raw pointers.
unsafe impl Send for CorsairEventUnion {}
unsafe impl Sync for CorsairEventUnion {}

#[repr(C)]
#[derive(Copy, Clone)]
pub union CorsairEventUnion {
    pub deviceConnectionStatusChangedEvent: *const CorsairDeviceConnectionStatusChangedEvent,
    pub keyEvent: *const CorsairKeyEvent,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairEventUnion"][::std::mem::size_of::<CorsairEventUnion>() - 8usize];
    ["Alignment of CorsairEventUnion"][::std::mem::align_of::<CorsairEventUnion>() - 8usize];
    ["Offset of field: CorsairEventUnion::deviceConnectionStatusChangedEvent"]
        [::std::mem::offset_of!(CorsairEventUnion, deviceConnectionStatusChangedEvent) - 0usize];
    ["Offset of field: CorsairEventUnion::keyEvent"]
        [::std::mem::offset_of!(CorsairEventUnion, keyEvent) - 0usize];
};

#[repr(C)]
#[derive(Copy, Clone)]
pub struct CorsairEvent {
    pub id: CorsairEventId,
    pub event_union: CorsairEventUnion,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairEvent"][::std::mem::size_of::<CorsairEvent>() - 16usize];
    ["Alignment of CorsairEvent"][::std::mem::align_of::<CorsairEvent>() - 8usize];
    ["Offset of field: CorsairEvent::id"][::std::mem::offset_of!(CorsairEvent, id) - 0usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairDataType_BooleanArray {}
unsafe impl Sync for CorsairDataType_BooleanArray {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDataType_BooleanArray {
    pub items: *mut bool,
    pub count: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDataType_BooleanArray"]
        [::std::mem::size_of::<CorsairDataType_BooleanArray>() - 16usize];
    ["Alignment of CorsairDataType_BooleanArray"]
        [::std::mem::align_of::<CorsairDataType_BooleanArray>() - 8usize];
    ["Offset of field: CorsairDataType_BooleanArray::items"]
        [::std::mem::offset_of!(CorsairDataType_BooleanArray, items) - 0usize];
    ["Offset of field: CorsairDataType_BooleanArray::count"]
        [::std::mem::offset_of!(CorsairDataType_BooleanArray, count) - 8usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairDataType_Int32Array {}
unsafe impl Sync for CorsairDataType_Int32Array {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDataType_Int32Array {
    pub items: *mut c_int,
    pub count: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDataType_Int32Array"]
        [::std::mem::size_of::<CorsairDataType_Int32Array>() - 16usize];
    ["Alignment of CorsairDataType_Int32Array"]
        [::std::mem::align_of::<CorsairDataType_Int32Array>() - 8usize];
    ["Offset of field: CorsairDataType_Int32Array::items"]
        [::std::mem::offset_of!(CorsairDataType_Int32Array, items) - 0usize];
    ["Offset of field: CorsairDataType_Int32Array::count"]
        [::std::mem::offset_of!(CorsairDataType_Int32Array, count) - 8usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairDataType_Float64Array {}
unsafe impl Sync for CorsairDataType_Float64Array {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDataType_Float64Array {
    pub items: *mut f64,
    pub count: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDataType_Float64Array"]
        [::std::mem::size_of::<CorsairDataType_Float64Array>() - 16usize];
    ["Alignment of CorsairDataType_Float64Array"]
        [::std::mem::align_of::<CorsairDataType_Float64Array>() - 8usize];
    ["Offset of field: CorsairDataType_Float64Array::items"]
        [::std::mem::offset_of!(CorsairDataType_Float64Array, items) - 0usize];
    ["Offset of field: CorsairDataType_Float64Array::count"]
        [::std::mem::offset_of!(CorsairDataType_Float64Array, count) - 8usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairDataType_StringArray {}
unsafe impl Sync for CorsairDataType_StringArray {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairDataType_StringArray {
    pub items: *mut *mut c_char,
    pub count: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDataType_StringArray"]
        [::std::mem::size_of::<CorsairDataType_StringArray>() - 16usize];
    ["Alignment of CorsairDataType_StringArray"]
        [::std::mem::align_of::<CorsairDataType_StringArray>() - 8usize];
    ["Offset of field: CorsairDataType_StringArray::items"]
        [::std::mem::offset_of!(CorsairDataType_StringArray, items) - 0usize];
    ["Offset of field: CorsairDataType_StringArray::count"]
        [::std::mem::offset_of!(CorsairDataType_StringArray, count) - 8usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairDataValue {}
unsafe impl Sync for CorsairDataValue {}

#[repr(C)]
#[derive(Copy, Clone)]
pub union CorsairDataValue {
    pub boolean: bool,
    pub int32: c_int,
    pub float64: f64,
    pub string: *mut c_char,
    pub boolean_array: CorsairDataType_BooleanArray,
    pub int32_array: CorsairDataType_Int32Array,
    pub float64_array: CorsairDataType_Float64Array,
    pub string_array: CorsairDataType_StringArray,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairDataValue"][::std::mem::size_of::<CorsairDataValue>() - 16usize];
    ["Alignment of CorsairDataValue"][::std::mem::align_of::<CorsairDataValue>() - 8usize];
    ["Offset of field: CorsairDataValue::boolean"]
        [::std::mem::offset_of!(CorsairDataValue, boolean) - 0usize];
    ["Offset of field: CorsairDataValue::int32"]
        [::std::mem::offset_of!(CorsairDataValue, int32) - 0usize];
    ["Offset of field: CorsairDataValue::float64"]
        [::std::mem::offset_of!(CorsairDataValue, float64) - 0usize];
    ["Offset of field: CorsairDataValue::string"]
        [::std::mem::offset_of!(CorsairDataValue, string) - 0usize];
    ["Offset of field: CorsairDataValue::boolean_array"]
        [::std::mem::offset_of!(CorsairDataValue, boolean_array) - 0usize];
    ["Offset of field: CorsairDataValue::int32_array"]
        [::std::mem::offset_of!(CorsairDataValue, int32_array) - 0usize];
    ["Offset of field: CorsairDataValue::float64_array"]
        [::std::mem::offset_of!(CorsairDataValue, float64_array) - 0usize];
    ["Offset of field: CorsairDataValue::string_array"]
        [::std::mem::offset_of!(CorsairDataValue, string_array) - 0usize];
};

// SAFETY: See CorsairEventUnion.
unsafe impl Send for CorsairProperty {}
unsafe impl Sync for CorsairProperty {}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct CorsairProperty {
    pub type_: CorsairDataType,
    pub value: CorsairDataValue,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairProperty"][::std::mem::size_of::<CorsairProperty>() - 24usize];
    ["Alignment of CorsairProperty"][::std::mem::align_of::<CorsairProperty>() - 8usize];
    ["Offset of field: CorsairProperty::type_"]
        [::std::mem::offset_of!(CorsairProperty, type_) - 0usize];
    ["Offset of field: CorsairProperty::value"]
        [::std::mem::offset_of!(CorsairProperty, value) - 8usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairLedColor {
    pub id: CorsairLedLuid,
    pub r: c_uchar,
    pub g: c_uchar,
    pub b: c_uchar,
    pub a: c_uchar,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairLedColor"][::std::mem::size_of::<CorsairLedColor>() - 8usize];
    ["Alignment of CorsairLedColor"][::std::mem::align_of::<CorsairLedColor>() - 4usize];
    ["Offset of field: CorsairLedColor::id"][::std::mem::offset_of!(CorsairLedColor, id) - 0usize];
    ["Offset of field: CorsairLedColor::r"][::std::mem::offset_of!(CorsairLedColor, r) - 4usize];
    ["Offset of field: CorsairLedColor::g"][::std::mem::offset_of!(CorsairLedColor, g) - 5usize];
    ["Offset of field: CorsairLedColor::b"][::std::mem::offset_of!(CorsairLedColor, b) - 6usize];
    ["Offset of field: CorsairLedColor::a"][::std::mem::offset_of!(CorsairLedColor, a) - 7usize];
};

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CorsairKeyEventConfiguration {
    pub keyId: CorsairMacroKeyId,
    pub isIntercepted: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CorsairKeyEventConfiguration"]
        [::std::mem::size_of::<CorsairKeyEventConfiguration>() - 8usize];
    ["Alignment of CorsairKeyEventConfiguration"]
        [::std::mem::align_of::<CorsairKeyEventConfiguration>() - 4usize];
    ["Offset of field: CorsairKeyEventConfiguration::keyId"]
        [::std::mem::offset_of!(CorsairKeyEventConfiguration, keyId) - 0usize];
    ["Offset of field: CorsairKeyEventConfiguration::isIntercepted"]
        [::std::mem::offset_of!(CorsairKeyEventConfiguration, isIntercepted) - 4usize];
};

// ---- Callback type aliases ----

pub type CorsairSessionStateChangedHandler = ::std::option::Option<
    unsafe extern "C" fn(context: *mut c_void, eventData: *const CorsairSessionStateChanged),
>;

pub type CorsairAsyncCallback =
    ::std::option::Option<unsafe extern "C" fn(context: *mut c_void, error: CorsairError)>;

pub type CorsairEventHandler =
    ::std::option::Option<unsafe extern "C" fn(context: *mut c_void, event: *const CorsairEvent)>;

// ---- Extern functions ----

unsafe extern "C" {
    #[must_use]
    pub fn CorsairConnect(
        onStateChanged: CorsairSessionStateChangedHandler,
        context: *mut c_void,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairGetSessionDetails(details: *mut CorsairSessionDetails) -> CorsairError;

    #[must_use]
    pub fn CorsairDisconnect() -> CorsairError;

    #[must_use]
    pub fn CorsairGetDevices(
        filter: *const CorsairDeviceFilter,
        sizeMax: c_int,
        devices: *mut CorsairDeviceInfo,
        size: *mut c_int,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairGetDeviceInfo(
        deviceId: *const c_char,
        deviceInfo: *mut CorsairDeviceInfo,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairGetLedPositions(
        deviceId: *const c_char,
        sizeMax: c_int,
        ledPositions: *mut CorsairLedPosition,
        size: *mut c_int,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairSubscribeForEvents(
        onEvent: CorsairEventHandler,
        context: *mut c_void,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairUnsubscribeFromEvents() -> CorsairError;

    #[must_use]
    pub fn CorsairConfigureKeyEvent(
        deviceId: *const c_char,
        config: *const CorsairKeyEventConfiguration,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairGetDevicePropertyInfo(
        deviceId: *const c_char,
        propertyId: CorsairDevicePropertyId,
        index: c_uint,
        dataType: *mut CorsairDataType,
        flags: *mut c_uint,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairReadDeviceProperty(
        deviceId: *const c_char,
        propertyId: CorsairDevicePropertyId,
        index: c_uint,
        property: *mut CorsairProperty,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairWriteDeviceProperty(
        deviceId: *const c_char,
        propertyId: CorsairDevicePropertyId,
        index: c_uint,
        property: *const CorsairProperty,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairFreeProperty(property: *mut CorsairProperty) -> CorsairError;

    #[must_use]
    pub fn CorsairSetLedColors(
        deviceId: *const c_char,
        size: c_int,
        ledColors: *const CorsairLedColor,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairSetLedColorsBuffer(
        deviceId: *const c_char,
        size: c_int,
        ledColors: *const CorsairLedColor,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairSetLedColorsFlushBufferAsync(
        callback: CorsairAsyncCallback,
        context: *mut c_void,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairGetLedColors(
        deviceId: *const c_char,
        size: c_int,
        ledColors: *mut CorsairLedColor,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairSetLayerPriority(priority: c_uint) -> CorsairError;

    #[must_use]
    pub fn CorsairGetLedLuidForKeyName(
        deviceId: *const c_char,
        keyName: c_char,
        ledId: *mut CorsairLedLuid,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairRequestControl(
        deviceId: *const c_char,
        accessLevel: CorsairAccessLevel,
    ) -> CorsairError;

    #[must_use]
    pub fn CorsairReleaseControl(deviceId: *const c_char) -> CorsairError;
}
